### PR TITLE
Rever

### LINKED ISSUE #1270: Add Release Automation
I think we could tighten the feedback loop on releasing h5py if we had a tool that helped us issue releases. 

I propose we add [rever](https://regro.github.io/rever-docs/) to h5py.  However, there may be other options out there (modeltee?).

### PR DESCRIPTION
**Pull request by scopatz**
This is an initial cut at support for rever (including having run `rever setup`). Closes #1270

### CODE REVIEW

**Comment by aragilar** [comment]
I agree with trying to move to hash based versioning if possible.

**Comment by takluyver** [comment]
I'm OK with requiring xonsh for making releases - this doesn't affect users or even typical contributors. Even if xonsh or rever were to disappear, the rever script would still be a useful reference for making a release manually or building a release process with some other tool.

**Comment by takluyver** [comment]
How far can you test this before it's merged? I'd like to get 2.10 out soon, so my inclination is to merge this once CI is passing, so you can make a release with it and fix bugs as they come up. Then we can add a bit to the docs about how to make a release afterwards.

-----

check-manifest failure:

```
lists of files in version control and sdist do not match!
missing from sdist:
  AUTHORS
  news
  news/TEMPLATE.rst
  news/existing.rst
  rever.xsh
suggested MANIFEST.in rules:
  include *.xsh
  include AUTHORS
  recursive-include news *.rst
```

pre-commit failure:

```
Fix End of Files.........................................................Failed
hookid: end-of-file-fixer
Files were modified by this hook. Additional output:
Fixing news/TEMPLATE.rst
Fixing AUTHORS
```

**Comment by scopatz** [comment]
> Can you get rever to do versioneer style hash-based versions between tags?

xonsh can work with versioneer (I think there is an example of this in conda-build). I am not super interested in adding this myself, but would happily review a PR :wink: 

> How far can you test this before it's merged? 

Pretty far. The `rever check` command makes sure that a user has the approriate permissions, everything is installed, and that everything for each of the activities used is in good working order.  

For most activities, there is the ability to use `rever --undo` in the event that something does go wrong. Obviously, there are some immutable actions (such as pushing to PyPI) that cannot be tested or undone until actual release time.  

> I'd like to get 2.10 out soon, so my inclination is to merge this once CI is passing, so you can make a release with it and fix bugs as they come up.

Yeah, sorry, I am finally back from all of my vactions.  I am working on this now.

**Comment by scopatz** [comment]
This is ready for review again

**Comment by takluyver** [comment]
I haven't learned about Rever to review this in detail, but it looks good at a brief glance. I'd still recommend we merge and iterate further in master.

**Comment by scopatz** [comment]
sounds good to me! btw this passed on travis, it just didn't report back correctly

**Comment by takluyver** [comment]
OK. Let's give the others a day or two to chime in, and merge if there are no objections.

**Comment by aragilar** [comment]
I cool with merging this.

**Comment by tacaswell** [comment]
CI is actually green, must have lost a webhook call.

**Comment by tacaswell** [comment]
I went a head and merged this as all but 1 active person with a commit-bit signed off on it.

**Comment by scopatz** [comment]
I can go ahead and try to cut the release now if folks are OK with that.

**Comment by tacaswell** [comment]
Do we want to finish off what is in https://github.com/h5py/h5py/milestone/16 ?

**Comment by scopatz** [comment]
I  ok with the PRs but I don't think we should block on issues

**Comment by scopatz** [comment]
Seems like there are no issues or PRs left on the milestone

**Comment by takluyver** [comment]
I don't think any of the last few issues & PRs are ready to finish quickly - I've already pushed before to get things landed, so the ones that were left are tricky issues and stragglers. So I've just bumped those issues off the milestone. Go for the release!

Obviously if the automation works well, it should be easier to make releases more often, so we don't need to worry about getting things done before release - there can always be another release soon.

**Comment by scopatz** [comment]
OK! I have gone for it!  2.10.0 has been cut.  Super easy.  If you see something wrong, let me know!

**Comment by takluyver** [comment]
Is there also automation for building any of the wheels, or does someone
need to do that?

**Comment by takluyver** [comment]
I see that Linux & (when it's working) Mac wheels are generated through https://github.com/MacPython/h5py-wheels - @tacaswell made a small commit to start that, and presumably downloaded and reuploaded the resulting wheels afterwards.

@tacaswell: I see you also uploaded Windows wheels. Is there some kind of automation for those?

**Comment by tacaswell** [comment]
no, those are from Cristoph Gohlke (we email him).

In previous releases I have created and pushed the tag, but waited until I had collected all of the wheels before uploading everything to pypi.  Sorry, I should have documented what I was doing better, I was basically following https://matplotlib.org/devdocs/devel/release_guide.html#all-releases (as that is the process I understand).

**Pull request merged**
