### PR TITLE
Fix float type collection in `_get_available_ftypes`

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/h5py/h5py/issues/1051

Makes use of NumPy's `typecodes` to get all of the floating typecodes and collect information about them into `available_ftypes` within `_get_available_ftypes`. This may make `_get_available_ftypes` ~50x faster (though this is probably unnoticeable) as it only checks known floating typecodes, types variables, and trusts NumPy's ordering. Simplifies the code a little bit as well. Most importantly this ensure the order is reliable across Python versions and OSes as the order is determined by NumPy in the `str` containing all of the floating typecodes; where, it has remained in ascending `itemsize` order at least for the last 8 years (i.e. NumPy 1.6.0). Though appears to have been there much longer and in order for that time.

ref: https://github.com/numpy/numpy/blob/v1.7.0/numpy/core/numerictypes.py#L907

### CODE REVIEW

**Comment by jakirkham** [comment]
This is done on my end. Would be great if someone could take a look. 😄

**Comment by tacaswell** [comment]
Nominally tagged for 2.9, will decide tomorrow if we should bump to 2.10 or not (and do the 2.9 tag!)

**Comment by tacaswell** [comment]
Moved to 2.10 so it can get tests and stew a bit longer...

**Comment by jakirkham** [comment]
Hmm...what is it we would be testing against here? Asking partially as it sounds like this function had no tests to begin with, correct?

**Comment by aparamon** [comment]
@jakirkham Not a unit test for `_get_available_ftypes`, but something more high-level like reported
````py
read_float = h5py.File(filename,'r')['test_group'].attrs['test_float']
cast_float = numpy.asscalar(read_float)
type(cast_float) # This returns either a python.float or a numpy.float64 at random
````

**Comment by aragilar** [comment]
The code which uses `_available_dtypes` assumes that it is ordered by "precision" (the number of bytes used to store is a good first approximation, but there are multiple formats which share the same size (x86 80 bit float on 64 bit system, double-double, ieee-quad), so byte size isn't the only factor), i.e. we want to find the smallest (in terms of byte size) numpy type which will hold the range stored in the HDF5 type (as it's both likely faster to use and requires less memory). A reasonable test could be to check that the byte size increases for each dtype in the tuple. Another one is to check that `maxexp` increases.

**Comment by jakirkham** [comment]
Here's a [link]( https://github.com/numpy/numpy/blob/v1.15.4/numpy/core/numerictypes.py#L888 )  to the definition of `Float` in `typecodes`. This is ordered by precision and has a fixed set of types. When I went through all of the types this function used previously, the type code of each `dtype` mapped to one of the characters in that `str` (if it was actually a floating point type and not something else like an integral type). Also that `str` has not changed for a long time and is ordered by size. Admittedly this was a month ago and I could have forgotten things.

**Comment by takluyver** [comment]
Where are we with this? Can we see a way to write a reasonable test for it? It seems like something that should go in for 2.10.

**Comment by jakirkham** [comment]
Sorry. I’m not currently working on this. I’d be ok closing, merging, or handing it off to someone to complete. Thoughts?

**Comment by takluyver** [comment]
My understanding from the thread above is that it's working, and the only hold up is a test. Is that right?

If so, I'd be OK either with someone else picking it up, or merging as is if we're confident enough that it won't cause regressions.

**Comment by jakirkham** [comment]
That sounds like an accurate summary.

SGTM

**Comment by takluyver** [comment]
I'll propose that we merge this without adding a specific test. If anyone objects, please speak up - I'll take silence as assent in a few days.

Rationale:

- It doesn't cause failures in any existing tests, including `test_float_round_tripping`, which checks that all numpy floating dtypes roundtrip correctly.
- Having read the various threads, I believe it fixes the issue as I understand it.
- It's simpler than the code it replaces.
- The problem only occurs intermittently on a platform that I don't use, so if I write a test, it's hard to be sure it's a useful one.

I'm all for thorough testing, but if we believe this code is an improvement, there's no particular point leaving it out for the lack of a test if no-one's prepared to write one.

If you disagree, please consider volunteering to write the test yourself! :wink: But even if you can't do that, make your objection known.

**Comment by takluyver** [comment]
OK, there have been no objections, so I'm going to merge this.

**Comment by jakirkham** [comment]
Thanks for seeing this one through, @takluyver. Hope it helps some people 🙂

**Pull request merged**
