### PR TITLE
MAINT: Add nightly wheel upload

### LINKED ISSUE #2353: Numpy 2.0 compat plan
I read through https://github.com/h5py/h5py/pull/2345#issuecomment-1839031905, https://github.com/numpy/numpy/issues/24300, and related issues and based on my (limited) understanding of the issue, I think that compiling with NumPy 2.0 will generate binaries that work with both NumPy >= 2.0 and NumPy < 2.0. As a downstream user of h5py I've been using this repo to use h5py nightlies (which I assume is managed by h5py maintainers?):

https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com

It has been possible for some months (and thus seemingly reliable by now) to get a 2.0.0.dev NumPy from https://pypi.anaconda.org/scientific-python-nightly-wheels/simple, and many other libraries (scikit-learn, scipy, etc.) now build their nightly wheels against itn. Would it be possible to migrate the `rackcdn.com` h5py binaries to build against NumPy 2.0.0.dev? Then downstream libraries (like mine) could resume testing against NumPy 2.0.0.dev *plus* h5py (and anything that depends on it). Currently we have to choose between testing NumPy 2.0.0.dev *or* h5py because libraries that build against NumPy < 2.0 (like h5py on `rackcdn`) can't be imported when using the NumPy 2.0.0.dev wheels.

### PR DESCRIPTION
**Pull request by larsoner**
Closes #2353

Trying to use https://github.com/git-for-windows/get-azure-pipelines-artifact for now but in case it doesn't work the direct JSON queries don't seem too bad actually.

Needs:

- [x] Get artifact working properly
- [x] Repackage properly
- [x] Remove TODO / uncomment lines
- [ ] @tacaswell add `secrets.ANACONDA_ORG_UPLOAD_TOKEN`

Then should be good to merge.

### CODE REVIEW

**Comment by larsoner** [comment]
@tacaswell based on https://github.com/h5py/h5py/actions/runs/7186963572/job/19573501403?pr=2355#step:7:58 I think I just need to take care of the TODO uncommenting steps and you need to add the secret, then we can merge and :crossed_fingers: . Does that sound right to you?

**Comment by tacaswell** [comment]
Finally looked at this, and realized I do not have the ability to generate these tokens like I thought I did.  Working on sorting out who does.

**Comment by tacaswell** [comment]
I've added the secret, but we can not test this with out merging so I'm going to go ahead and merge it.

**Comment by tacaswell** [comment]
@larsoner Something is not going right with the "download the wheels" step.

**Comment by tacaswell** [comment]
https://github.com/h5py/h5py/actions/runs/8014434969/job/21893113138

**Comment by larsoner** [comment]
I am really confused because looking at what [the URL the action uses](https://github.com/git-for-windows/get-azure-pipelines-artifact/blob/99f8b207e11b8528400c2914bacb12d232f583bb/src/downloader.ts#L155C16-L155C126):

https://dev.azure.com/h5pyappveyor/h5py/_apis/build/builds?definitions=1&statusFilter=completed&resultFilter=succeeded&reasonFilter=individualCI&$top=1

I get a nice 1-count  list that points [to the right build](https://dev.azure.com/h5pyappveyor/347aa760-c0ad-4566-98fe-98d2281065ee/_build/results?buildId=1870). And then over in #2383 things [are fine](https://github.com/h5py/h5py/actions/runs/8015326719/job/21895313031?pr=2383). Maybe just try restarting the CIs again?

**Comment by tacaswell** [comment]
I re-ran the action this morning and it worked!

I suspect I was too impatient and tried running the action before azure had fully finished so maybe I was losing the race. 

Sorry for the noise....

**Comment by larsoner** [comment]
No problem, awesome that it's working!

**Pull request merged**
