### PR TITLE
Explicity specify endianess of expected output type

### PR DESCRIPTION
**Pull request by mraspaud**
This should address #816 

Signed-off-by: Martin Raspaud <martin.raspaud@smhi.se>

### CODE REVIEW

**Comment by ghisvail** [comment]
I can confirm the proposed commit fixes builds on `mips` and `s390x`. Thanks @mraspaud

**Comment by jrtc27** [comment]
I don't know what h5py's policy is, but to me, there shouldn't be whitespace-only changes bundled in with this commit, as it's hard to see at a glance (without git diff -w) which lines were actually changed.

**Comment by mraspaud** [comment]
Ok, sorry about that. Tell me if I need to revert this.

**Comment by tacaswell** [comment]
I would not worry about the whitespace changes.

**Pull request merged**
