### PR TITLE
Fix virtual dataset

### PR DESCRIPTION
**Pull request by dota17**
### major change:
+ specify dtype in VirtualLayout, fix issue #1474 
+ change the default dtype to float64 for dataset (in numpy, the default for float is float64 regardless of the system).

CC: @takluyver

### CODE REVIEW

**Comment by takluyver** [comment]
The idea from #1474 was to require a dtype in `VirtualLayout`, i.e. not provide any default. The obvious default in most cases is whatever the dtype of the source data is, but that's a bit tricky for various reasons (see [this comment](https://github.com/h5py/h5py/issues/1474#issuecomment-667207562)), so it's better to make it explicit than to surprise the user with a guess.

I'm not sure about changing the default dtype if you create a dataset with no dtype and no data. Matching numpy is nice, but so is consistency from one version to the next. Even when we're heading for 3.0, I don't think we should change everything just because we can.

**Comment by takluyver** [comment]
@tacaswell @aragilar & anyone else who's interested: thoughts on changing the default dtype? I'm -0.5 on it.

**Comment by aragilar** [comment]
If anything, I would think not having a default type would be better (either you provide the data, or you provide the type), -1 from me.

**Comment by dota17** [comment]
Ok @aragilar  @takluyver I will leave it as-is.

**Comment by takluyver** [comment]
@dota17 to be clear, we're suggesting a change from the current code. Currently it defaults to float32, and this PR makes the default float64. We're suggesting removing the default (in `VirtualLayout`), so the user has to pass a dtype in explicitly.

I'm going to close this because I think it would be easier to do this change in a new pull request, but we can reopen this one if you prefer.

**Pull request closed without merging**
