### PR TITLE
Add Dataset.is_scale() method

### PR DESCRIPTION
**Pull request by ajelenak**
Implements what was proposed in #2125.

### CODE REVIEW

**Comment by takluyver** [comment]
Should we make this a property (so you'd use e.g. `if dset.is_scale:` without `()`)? We already have `.is_virtual` as a property, so it would seem natural to follow that pattern, and I doubt we'd ever need parameters for it.

**Comment by ajelenak** [comment]
I agree. Made the required changes.

**Comment by epourmal** [comment]
Just FYI in case you want to consider... 

HDF5 has a configure option to use new object references for dimensions scales `--enable-dimension-scales-with-new-ref`. It was introduced in 1.12. 2( or 1?) for enabling DS interface with VOL connectors. See also [H5DSwith_new_ref](https://docs.hdfgroup.org/hdf5/develop/group___h5_d_s.html#gaed2b97139202dfe69f3f2a7364c10fbc). New object references are default for dimension scales for non-native VOL connectors.

**Comment by ajelenak** [comment]
This PR is about using [`H5DSis_scale()`](https://docs.hdfgroup.org/hdf5/develop/group___h5_d_s.html#title9). Does this function behaves differently for new HDF5 object references?

**Comment by epourmal** [comment]
> This PR is about using [`H5DSis_scale()`](https://docs.hdfgroup.org/hdf5/develop/group___h5_d_s.html#title9). Does this function behaves differently for new HDF5 object references?

I don't think this is a problem for h5py based on 1.12.2 and later since the function will be returning true or false as expected. The problem is in possible file incompatibility if the file was created with a pass-through VOL connector: a non-native VOL connectors always trigger usage of  new references in spite of the terminal VOL connector being a native one! plus the library may be configured to use new references in the first place. A user will be even not aware of incompatibility until he/she uses HDF5 software based on 1.10.* or earlier to read the file back. I hope the library will handle the case gracefully, but I don't think it was tested.

This is an HDF5 problem and has to be addressed there. I just wanted to raise awareness of possible HDF5 file backward compatibility issue. Maybe h5py as a high-level API has a better way of dealing with such issues until HDF5 fixes the problem and uses old references when a terminal connector is a native one. 

As you can see this is a slightly different problem from `is_virtual`.

h5py community was warned :-)

**Comment by ajelenak** [comment]
Closes #2125.

**Pull request merged**
