### PR TITLE
DEP: drop support for CPython 3.8

### PR DESCRIPTION
**Pull request by neutrinoceros**
Python 3.8 will be EOL in less than 2 months, and the previous such bump happened more than a year ago (https://github.com/h5py/h5py/pull/2262), so I figured I would go for it now.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I forgot we had some unresolved CI failures. Well, keeping this as a draft for now.

**Review by larsoner — APPROVED** [review]
Simplifies some stuff which is great!

Hopefully the CIs come back happy :crossed_fingers:

**Comment by larsoner** [comment]
Did you want to put in https://github.com/h5py/h5py/pull/2464#discussion_r1715337851 as well now that you can?

**Comment by neutrinoceros** [comment]
yeah why not. Thanks for reminding me !

**Comment by takluyver** [comment]
Don't forget to write a release note (https://docs.h5py.org/en/stable/contributing.html#write-a-release-note ). Otherwise, this looks good to me, thanks.

**Comment by neutrinoceros** [comment]
@takluyver done !

**Comment by takluyver** [comment]
I'm just going to close/reopen to re-run the tests with the CI (hopefully) fixed.

**Pull request merged**
