### PR TITLE
Test with python 3.5

### PR DESCRIPTION
**Pull request by aragilar**

### CODE REVIEW

**Comment by aragilar** [comment]
Failing because of https://github.com/travis-ci/travis-ci/issues/4794, we could work around this, or we could wait for it to be fixed (at least for me, the tests do pass on 3.5 in Debian).

**Comment by jakirkham** [comment]
Would be nice to have 3.5 testing indeed.

**Comment by jakirkham** [comment]
Merge conflicts.

**Comment by aragilar** [comment]
Rebased, should be no conflicts.

**Comment by aragilar** [comment]
Failing because of https://github.com/numpy/numpy/issues/7498

**Comment by aragilar** [comment]
Rebased to include the fix for numpy, and with some because of how yaml/travis deals with comments and includes.

**Comment by andrewcollette** [comment]
Thanks!

**Pull request merged**
