### PR TITLE
FIX: Support hdf5 1.10.3

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
I am not worried about the change to account for swmr as that major, minor error code pair only appears 2x in the code base and is new in 1.10.3 (these searches are over the 1.10.{2,3,4} code bases)

```
23:10 $ ack 'H5E_FILE, H5E_CANTCONVERT'
hdf5-1.10.3/src/H5F.c
1347:        HGOTO_ERROR(H5E_FILE, H5E_CANTCONVERT, FAIL, "unable to convert file format")
1519:   HGOTO_ERROR(H5E_FILE, H5E_CANTCONVERT, FAIL, "unable to convert file format")

hdf5-1.10.4/src/H5F.c
1347:        HGOTO_ERROR(H5E_FILE, H5E_CANTCONVERT, FAIL, "unable to convert file format")
1519:   HGOTO_ERROR(H5E_FILE, H5E_CANTCONVERT, FAIL, "unable to convert file format")

```

I am more worried about the fix for `len` as that pair appears a lot of places:

```
23:51 $ ack 'H5E_SYM, H5E_BADTYPE'
hdf5-1.10.3/src/H5Gtest.c
677:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "symbol table information is not cached")

hdf5-1.10.3/src/H5Gint.c
325:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, NULL, "not a group")

hdf5-1.10.3/src/H5Gobj.c
142:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a property list")

hdf5-1.10.3/src/H5Gname.c
1130:                                HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not valid object type")

hdf5-1.10.3/src/H5Gcompact.c
628:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
630:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type")

hdf5-1.10.3/src/H5Gdeprec.c
407:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
409:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
538:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
540:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
581:    HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
982:    HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location ID")
1025:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a group")
1065:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
1261:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location ID")
1265:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "can't get object name")
1300:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a group")
1341:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't get object type")
1380:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "not a group")

hdf5-1.10.3/src/H5Gdense.c
1844:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
1846:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type")

hdf5-1.10.2/src/H5Gtest.c
621:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "symbol table information is not cached")

hdf5-1.10.2/src/H5Gint.c
294:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, NULL, "not a group")

hdf5-1.10.2/src/H5Gobj.c
146:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a property list")

hdf5-1.10.2/src/H5Gname.c
1133:                                HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not valid object type")

hdf5-1.10.2/src/H5Gcompact.c
633:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
635:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type")

hdf5-1.10.2/src/H5Gdeprec.c
1045:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "can't get object name")
1083:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "not a group")
1087:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't get object type")

hdf5-1.10.2/src/H5Gdense.c
1877:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
1879:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type")

hdf5-1.10.4/src/H5Gtest.c
677:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "symbol table information is not cached")

hdf5-1.10.4/src/H5Gint.c
325:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, NULL, "not a group")

hdf5-1.10.4/src/H5Gobj.c
142:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a property list")

hdf5-1.10.4/src/H5Gname.c
1130:                                HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not valid object type")

hdf5-1.10.4/src/H5Gcompact.c
628:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
630:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type")

hdf5-1.10.4/src/H5Gdeprec.c
407:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
409:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
538:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
540:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
581:    HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
982:    HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location ID")
1025:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a group")
1065:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location")
1261:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a location ID")
1265:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "can't get object name")
1300:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, FAIL, "not a group")
1341:   HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't get object type")
1380:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "not a group")

hdf5-1.10.4/src/H5Gdense.c
1844:            HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "can't determine object type")
1846:        HGOTO_ERROR(H5E_SYM, H5E_BADTYPE, H5G_UNKNOWN, "unknown link type"
```

but it is not clear how many of those code paths we actually use (and it is clear that we don't test them if we do!).  Not sure fixing an API change that we test is worth the cost of breaking some APIs that we do not.

**Comment by aragilar** [comment]
For the len case, we could catch the `TypeError` at https://github.com/h5py/h5py/blob/07f3c362887563c1040b10d2cbd8cca49ceac1b9/h5py/h5g.pyx#L330 and raise it as a ValueError (it looks like that function is deprecated anyway, so we'll probably need to look at what the new error will be once we use the 1.8 API).

**Comment by takluyver** [comment]
Is it only getting the number of objects for a closed file that's affected, or are there similar changes to the error codes for lots of operations?

Do we know why libhdf5 changed like this? If the error codes are part of the library's API, it looks like a breaking API change in a patch release.

**Comment by tacaswell** [comment]
This patch is now vendored into conda-forge ( https://github.com/conda-forge/h5py-feedstock/pull/43 )

**Comment by takluyver** [comment]
I have posted about this on the HDF5 forum: https://forum.hdfgroup.org/t/hdf5-error-number-changes-in-1-10-3/5013

I'm not encouraged that I can't find the error numbers (H5E_ARGS, H5E_SYM, etc.) themselves documented anywhere. The functions to access them are documented, but not the possible numbers, unless I've failed to find them.

If the HDF group don't consider the error numbers part of the public API, I don't think that h5py can really guarantee how errors get translated into Python exceptions.

**Comment by tacaswell** [comment]
I am 50/50 on https://github.com/h5py/h5py/pull/1099#issuecomment-431668832 

On one hand, it reduces the surface area of the change, on the other hand it special cases this one and confuses the traceback a bit (as we can not use `raise .. from ...` on py2).

**Comment by takluyver** [comment]
Yup, that's why I was wondering if it was just that method that was affected. If the exception has changed for any operation you try to do on a closed file, then special-casing `get_num_objs()` might make the test pass, but it doesn't solve the broader problem.

**Comment by takluyver** [comment]
The word from the HDF5 group amounts to: we can't really rely on the error numbers ([full answer](https://forum.hdfgroup.org/t/hdf5-error-number-changes-in-1-10-3/5013/2?u=thomas1)).

Given that, I'd be inclined to apply the SWMR change that you're relatively confident of, but not the other change, for `len()` of closed groups. I'd change or skip the relevant test for now, and leave the error doing what it does rather than risking introducing other changes.

Longer term, it seems like having a lookup table to map HDF5 errors to Python errors isn't reliable. We could just use a general HDF5Error class and expose the error codes directly for users to deal with (I think this was tried before; presumably there were reasons for moving away from it). Or we could translate exceptions within each function, rather than having a global mapping.

**Comment by takluyver** [comment]
Even longer term, I've asked if we can get POSIX errnos exposed; that would let us properly convert some errors to OSError. But there's no word yet on whether they'll go for that, and even if they do, it will be a long time before we can rely on it.

**Comment by tacaswell** [comment]
Removed the test on `len` and removed that associated re-mapping.

Any thoughts on where we should document that the error types will not be stable?

**Comment by tacaswell** [comment]
Plan to self merge this is 15 hours.

**Comment by takluyver** [comment]
I'd say either at the end of the quick start guide, or in the FAQ. Neither's a perfect place for it, but I feel like it belongs with that kind of general info.

**Comment by tacaswell** [comment]
Pushed docs, will merge once it passes.

**Pull request merged**
