### PR TITLE
Move from six.PY3 to six.PY2

### PR DESCRIPTION
**Pull request by aragilar**
Switch to checking six.PY2, instead of six.PY3. This should prevent some breakage for a potential python 4 release as per https://astrofrog.github.io/blog/2016/01/12/stop-writing-python-4-incompatible-code/.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: 

If you are feeling very paranoid, might want to not touch the test files.

**Comment by andrewcollette** [comment]
I don't have any objection to this.  Looks like there are some conflicts at the moment, though.

**Comment by jakirkham** [comment]
Would like to see this change in. :)

**Comment by aragilar** [comment]
Rebased, tests failing because of https://github.com/numpy/numpy/issues/7498, hopefully numpy 1.11.1 comes out soon.

**Comment by aragilar** [comment]
Rebased again (to include the fix for numpy), so this should be fine to merge.

**Pull request merged**
