### PR TITLE
Base compound type size off of numpy itemsize

### PR DESCRIPTION
**Pull request by cmorse**
This was causing some interoperability issues with some C hdf5 code that expects the sizeof datatypes to be a multiple of 8 (The same value that numpy's itemsize uses).

### CODE REVIEW

**Comment by lnunno** [comment]
I would like to see this merged in as well.

**Comment by cmorse** [comment]
Not sure why github closed this for me. @andreabedini, @andrewcollette Would appreciate some feedback on this PR.

**Comment by AcidLeroy** [comment]
It would be great to have this.

**Comment by andreabedini** [comment]
@cmorse first of all sorry for the delay in getting back to you. I had a look and I am not sure that problem this is supposed to fix (honest question).

Doing `tid = H5Tcreate(H5T_COMPOUND, dt.itemsize)` does seem more sensible but looking at HDF5 code, it doesn't look like the size is really used anywhere in `H5T__create` and also `H5T__insert` seems to have logic to keep track of the total size of the members.

**Comment by andreabedini** [comment]
oh! I see. Calling `H5Tget_size` on the type created by h5py will return just 1, is this what you are experiencing? (HDF5 API is a bit weird here)

**Comment by cmorse** [comment]
@andreabedini No worries.

The problem this pull request is trying to fix is that in the project I am working on, we are intentionally putting additional padding at the end of datatypes to allow for future expansion. The additional padding is used so that additional fields can be added in the future. When the datatype defined lacks the padding, it's size doesn't line up with what's expected elsewhere in our code, which causes problems with reading the data.

**Comment by aragilar** [comment]
@cmorse I combined this and #738 in #793 (plus some additional compound datatype work), can you see if the latest master fixes your problem?

**Comment by cmorse** [comment]
@aragilar Sorry for the late reply on this. A coworker has verified that #738 fixes the issue we were having.

**Pull request closed without merging**
