### PR TITLE
Nicer API for specifying a filter and options

### PR DESCRIPTION
**Pull request by takluyver**
This is a rough draft of an idea I mentioned on #1315. The idea is that from the user perspective, something like this would be possible:

```python
f.create_dataset('foo', data=numpy.arange(100),
    compression=hdf5plugin.Blosc(level=9, shuffle='byte'))
```

For hdf5plugin, the code would look something like this:

```python
from h5py.filters import FilterRefBase

class Blosc(FilterRefBase):
    filter_id = 32001
    def __init__(self, level, shuffle='bit', compression='blosclz'):
        self.filter_options = (0, 0, 0, 0, level, shuffle, compression)
```

### CODE REVIEW

**Comment by t20100** [comment]
That sounds good to me, we'll update hdf5plugin to be compatible with it.

**Comment by takluyver** [comment]
I saw that you'd like to use the same object for `**kwargs` style usage with the existing h5py API. I'm not sure how easy that is with this design. Have you investigated it at all?

**Comment by takluyver** [comment]
OK, I got curious. I think the last commit should allow for using it as **kwargs as well. Of course, you'd have to have a fallback copy of that class to use with existing versions of h5py that don't provide it.

Alternatively, we could make it so that the user uses a property to get the **kwargs:

```python
f.create_dataset('foo', data=numpy.arange(100),
    **hdf5plugin.Blosc(level=9, shuffle='byte').kw)
```

That's slightly more typing, but slightly less magic.

**Comment by t20100** [comment]
Great, I was thinking of doing it on our side, but it is best if it is in `h5py`.

I would go for:
```
f.create_dataset('foo', data=numpy.arange(100),
    **hdf5plugin.Blosc(level=9, shuffle='byte'))
```

That's probably what people will write for a little while for 2.x, 3.x compatibility... and probably until you eventually deprecate `compression_opts`.

**Comment by aragilar** [comment]
I think having the plugin being a mapping is probably the nicer API. Does anyone have any objections to this being merged?

**Comment by kif** [comment]
I like this PR. Makes sense.

**Comment by scopatz** [comment]
LGTM

**Pull request merged**
