### PR TITLE
Set up CI for Python 3.10

### PR DESCRIPTION
**Pull request by takluyver**
This probably isn't going to work straight away, but I thought I'd get started on this before the inevitable bug reports roll in.

### CODE REVIEW

**Comment by takluyver** [comment]
Building the wheels on Linux & Windows seems to be working now, but testing fails until Python 3.10 is available on Azure pipelines (https://github.com/actions/virtual-environments/issues/4226).

NumPy wheels for 3.10 are only there for Linux so far. We'll probably want to wait for NumPy wheels on Windows & Mac as well.

**Comment by takluyver** [comment]
It could be - I don't know in any detail what cibuildwheel does on Mac (on Linux it runs a docker container)

**Comment by takluyver** [comment]
I'll merge this as is, and make a PR to re-add the Mac 3.10 wheels.

**Comment by takluyver** [comment]
Done as #1987.

The question now is whether we should get a release out with Python 3.10 wheels for Linux & Windows, or wait for the Mac issue to be solved first. I might give it a few days to see if someone finds a quick solution. But we can always do another release later.

**Comment by cclauss** [comment]
@henryiii Is there any insight that you can offer on the Mac issue?

**Comment by henryiii** [comment]
This is weird. It seems like `NPY_COMPLEX256` is False but `COMPLEX256_SUPPORT` is true? But only for macOS & Python 3.10? Where is numpy coming from? I'd assume for NPY_COMPLEX256 you'd need numpy installed, but it's not in your pyproject.toml. I see it in `setup_requires`, but `setup_requires` is deprecated and doesn't work very well; I'm not sure how it would interact here with the PEP 518 requirements. Obviously it's getting at least Cython, and some version of numpy, but maybe checking which one would be helpful.

**Comment by henryiii** [comment]
Do you have any testing on macOS 3.10? I don't think the build process here is touched, particularly, so I'd assume whatever is broken in the build here would be locally too. The weird blend of old, deprecated `setup_requires` and PEP 517 builds with 518 requirements is really weird. I'd move all the build requirements (Cython and numpy) to PEP instead of manually trying to make the lower pins, and use https://github.com/scipy/oldest-supported-numpy for the build requirements; that's what it's for.

**Comment by takluyver** [comment]
I'm fairly involved in packaging, and from what I know, `setup_requires` should work just as well as specifying PEP 518 requirements for the time being. Feel free to prove me wrong, though! :slightly_smiling_face: 

I agree that we'll need to do something different in the future - see the discussion on #1981 for more about why it's that way at the moment and what we might do in the future.

**Comment by henryiii** [comment]
I get exactly the same thing locally that is seen on cibuildwheel:

```console
$ gh repo clone h5py/h5py
$ cd h5py/
$ brew install hdf5
$ /usr/local/opt/python@3.10/bin/python3 -m venv .venv
$ .venv/bin/pip install .
Processing /Users/henryschreiner/git/software/h5py
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.21.3
  Using cached numpy-1.21.3-cp310-cp310-macosx_10_9_universal2.whl (27.2 MB)
Building wheels for collected packages: h5py
  Building wheel for h5py (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/henryschreiner/git/software/h5py/.venv/bin/python3.10 /Users/henryschreiner/git/software/h5py/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/tmpq1nfvwcq
       cwd: /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-kxtwjtgp
  Complete output (302 lines):
  running bdist_wheel
  running build
  running build_py
  creating build

...

  building 'h5py.h5t' extension
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -DH5_USE_18_API -DNPY_NO_DEPRECATED_API=0 -I./h5py -I/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/lzf -I/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/lzf/lzf -I/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-build-env-5ui7b7e6/normal/lib/python3.10/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/henryschreiner/git/software/h5py/.venv/include -I/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c -o build/temp.macosx-11-x86_64-3.10/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.o
  /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c:18321:20: error: use of undeclared identifier 'h5py_size_n256'
      __pyx_v_size = h5py_size_n256;
                     ^
  /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c:18330:21: error: use of undeclared identifier 'h5py_offset_n256_real'
      __pyx_v_off_r = h5py_offset_n256_real;
                      ^
  /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c:18339:21: error: use of undeclared identifier 'h5py_offset_n256_imag'
      __pyx_v_off_i = h5py_offset_n256_imag;
                      ^
  /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c:18947:20: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
    if (((__pyx_t_12 > __pyx_t_9) != 0)) {
          ~~~~~~~~~~ ^ ~~~~~~~~~
  /private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pip-req-build-oimh0xqv/h5py/h5t.c:18967:40: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
    __pyx_t_11 = ((__pyx_v_member_offset > __pyx_cur_scope->__pyx_v_dt->elsize) != 0);
                   ~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  2 warnings and 3 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for h5py
Failed to build h5py
ERROR: Could not build wheels for h5py which use PEP 517 and cannot be installed directly
```

**Comment by henryiii** [comment]
I wonder if there's a bug in the macOS 3.10 numpy wheels that cause the results for 256-bit support to be misreported?

**Comment by henryiii** [comment]
This fails in the same way, which makes me think it's not a setup_requires issue:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 388ef115..594c08b3 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -1,5 +1,13 @@
 [build-system]
-# Further build requirements - like numpy & cython - come from setup.py via
-# the PEP 517 interface.
-requires = ["setuptools", "wheel"]
+# Further build requirements - like mpi come from deprecated setup_requires
+# setup.py usage
 build-backend = "setuptools.build_meta"
+requires = [
+    "setuptools",
+    "wheel",
+    'pkgconfig',
+    "Cython >=0.29; python_version<'3.8'",
+    "Cython >=0.29.14; python_version=='3.8'",
+    "Cython >=0.29.15; python_version>='3.9'",
+    "oldest_supported_numpy",
+]
diff --git a/setup.py b/setup.py
index 6bbab23a..4e85f25e 100755
--- a/setup.py
+++ b/setup.py
@@ -24,19 +24,11 @@ import setup_build, setup_configure

 VERSION = '3.5.0'

-# Minimum supported versions of Numpy & Cython depend on the Python version
-NUMPY_MIN_VERSIONS = [
-    # Numpy    Python
-    ('1.14.5', "=='3.7'"),
-    ('1.17.5', "=='3.8'"),
-    ('1.19.3', "=='3.9'"),
-    ('1.21.3', ">='3.10'"),
-]

 # these are required to use h5py
-RUN_REQUIRES = ["cached-property; python_version<'3.8'"] + [
-    f"numpy >={np_min}; python_version{py_condition}"
-    for np_min, py_condition in NUMPY_MIN_VERSIONS
+RUN_REQUIRES = [
+    "cached-property; python_version<'3.8'",
+    "numpy >=1.17.5",
 ]

 # these are required to build h5py
@@ -44,15 +36,7 @@ RUN_REQUIRES = ["cached-property; python_version<'3.8'"] + [
 # supported version; h5py wheels should then work with newer versions of these.
 # Downstream packagers - e.g. Linux distros - can safely build with newer
 # versions.
-SETUP_REQUIRES = [
-    'pkgconfig',
-    "Cython >=0.29; python_version<'3.8'",
-    "Cython >=0.29.14; python_version=='3.8'",
-    "Cython >=0.29.15; python_version>='3.9'",
-] + [
-    f"numpy =={np_min}; python_version{py_condition}"
-    for np_min, py_condition in NUMPY_MIN_VERSIONS
-]
+SETUP_REQUIRES = []

 if setup_configure.mpi_enabled():
     RUN_REQUIRES.append('mpi4py >=3.0.2')
```

**Comment by henryiii** [comment]
FYI, setup_requires is now officially depreceted as of Oct 22, in setuptools 58.3.0:

> Officially deprecated support for setup_requires. Users are encouraged instead to migrate to PEP 518 build-system.requires in pyproject.toml. Users reliant on setup_requires should consider pinning to this major version to avoid disruption.

**Comment by henryiii** [comment]
Possibly of interest for the long term: https://iscinumpy.dev/post/scikit-build-proposal/ ?

**Comment by takluyver** [comment]
Thanks. At present, however, I'm more interested in the work happening on Scipy to build with Meson. My impression is that Meson has enough momentum and is a tool people are excited about, whereas CMake is something that people use because it's there, it's familiar, it's the default option that no-one would be fired for picking. I haven't used either extensively, so I'd rather learn about the new one. I see you say that modern CMake is pleasant compared to how it used to be, but I'm afraid I take this with a pinch of salt - I think people familiar with a given language always overestimate how much the latest round of modernisation will help newcomers (I'm sure I'm as guilty of this as anyone).

My current thinking is to wait until scipy has this at a point where it can build Python packages (sdists & wheels), and then start looking at how we could use it for h5py.

**Comment by henryiii** [comment]
I'll write a longer comparison of the two eventually - I find several of Meson's decisions to be problematic, and some of the common complaints are just as present in Meson as CMake, and it is very opinionated, to the point I expect to be unusable for certain large projects. It's also surprisingly close to CMake; you can very much see what influenced Meson. Rewriting something without providing a compelling reason it's better other than "no old bad tutorials and examples!" is not a great idea, IMO. I haven't dumped Python for Julia or some other newer, "less baggage" language either.

But I do like some aspects of Meson, and I plan to become a bit more familiar with it in practice. Their entry-level docs are fantastic, for example. I think it's okay for smaller projects; so far it's replacing autotools more than CMake; anything the reduces autotools is good, IMO. :)

Also you are currently 27 times more likely to already have a CMake build vs. a Meson one; HDF5 already has a CMake build and it doesn't have a Meson one, as far as I can tell. I don't think a configuration tool requiring a runtime in some other language (like SCONS, Waf, or Meson) can become the "default" build system for a compiled language, any more than Rake could replace Make, even though it was superior. There is a C++ port, though, so maybe that will change.

We will be collaborating with the SciPy Meson project as well, trying to solve common problems, and more choice is a good thing. If this proposal gets funded, it will help Meson move forward too. In fact, they are already dependent on scikit-build/ninja-python-distributions. :)

**Pull request merged**
