### PR TITLE
Fix fillvalue for strings

### LINKED ISSUE #941: Setting fillvalue for datasets with variable length string dtype
This does not appear to work:
```
In [34]: f = h5py.File('varlenstr.h5')

In [35]: vlen_str = h5py.special_dtype(vlen=str)

In [36]: f.create_dataset('foo', (2,), dtype=vlen_str, fillvalue='bar')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-ace807cb8186> in <module>()
----> 1 f.create_dataset('foo', (2,), dtype=vlen_str, fillvalue='bar')

~/conda/envs/xarray-netcdf4-py36/lib/python3.6/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    106         """
    107         with phil:
--> 108             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    109             dset = dataset.Dataset(dsid)
    110             if name is not None:

~/conda/envs/xarray-netcdf4-py36/lib/python3.6/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
    119     if fillvalue is not None:
    120         fillvalue = numpy.array(fillvalue)
--> 121         dcpl.set_fill_value(fillvalue)
    122
    123     if track_times in (True, False):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2846)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/_objects.c:2804)()

h5py/h5p.pyx in h5py.h5p.PropDCID.set_fill_value (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5p.c:5073)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5t.c:17938)()

h5py/h5t.pyx in h5py.h5t.py_create (/Users/ilan/minonda/conda-bld/h5py_1496887972496/work/h5py/h5t.c:17897)()

TypeError: No conversion path for dtype: dtype('<U3')
```

Summary of the h5py configuration:
<details>
h5py    2.7.0,
HDF5    1.8.17,
Python  3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59),
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)],
sys.platform    darwin,
sys.maxsize     9223372036854775807,
numpy   1.13.1
</details>

### PR DESCRIPTION
**Pull request by aragilar**
Tests are currently not passing (I suspect it will need the changes from #1608). This code has apparently been floating in my fork for a while.

Closes #941.

### CODE REVIEW

**Comment by takluyver** [comment]
Closing & reopening to re-run the tests with #1608 merged.

**Comment by takluyver** [comment]
Still no dice, it would seem:

```
RuntimeError: Can't get creation plist (address of object past end of allocation)
```

**Comment by aragilar** [comment]
Well, that's disappointing, I'll spend some more time digging into this.

**Comment by kmuehlbauer** [comment]
@aragilar Whatt is the current status of this PR? Is this still considered for implementation? Thanks!

**Comment by kmuehlbauer** [comment]
@aragilar Did you had the chance to pursue this issue?

**Comment by aragilar** [comment]
@kmuehlbauer No, I haven't looked at this in ages, but feel free to use (or not use) this to try to get a complete fix.

**Comment by kmuehlbauer** [comment]
Thanks @aragilar ofr letting me know.

**Comment by kmuehlbauer** [comment]
@aragilar I've built on your commit in #2044.

**Comment by kmuehlbauer** [comment]
Might be closed since #2044 is in.

**Comment by takluyver** [comment]
Indeed, this can be closed now.

**Pull request closed without merging**
