### PR TITLE
FIX: remove `base.MappingHDF5` from `dims.DimensionManager`

### PR DESCRIPTION
**Pull request by kmuehlbauer**
- remove `base.MappingHDF5` from `dims.DimensionManager` to not add unneeded Mapping properties
- resolves https://github.com/h5py/h5py/issues/744

Update: Description changed and force-pushed

### CODE REVIEW

**Comment by scopatz** [comment]
This seems like an API break

**Comment by kmuehlbauer** [comment]
@scopatz Why?

**Comment by kmuehlbauer** [comment]
Maybe a bit more context:
`DimensionManager` inherits from `base.MappingHDF5`. So `key`, `value` and `item` are exposed to the public API, but are broken by design. This PR fixes this. If `DimensionManager` is thought to work as sequence, then it should not inherit from Mapping but from Sequence, or do I miss something (which might be the case)?

**Comment by takluyver** [comment]
Presumably this is an API break in the sense that code doing `for dim in ds.dims` would need to change?

My feeling is that the `ds.dims` interface is more like a sequence - the 'keys' are always a consecutive group of integers from 0 to N-1, if I'm reading it right. It sounds like most mapping methods are broken at the moment, so maybe we should just make it a mapping? I guess that would break `__contains__` (`i in ds.dims`), but it seems unlikely much code is using that. Do you see anything else it will break? How do equality checks work? I'm looking at the list of Mapping methods in https://docs.python.org/3/library/collections.abc.html#module-collections.abc

**Comment by kmuehlbauer** [comment]
@scopatz Maybe this inheritance from `base.MappingHDF5` isn't needed at all (by looking at the code).

I tried to follow the code in git commit history. It was copied over from `AttributeManager` but the inheritance wasn't ever changed. The `MappingHDF5` properties (keys, values, items) are never used, weren't even indented to be used (citing the docstring: "...Represents a collection of dimensions..."). Also the documentation has no sign of using keys, values, items, but shows that iteration is sequence like.

**Comment by kmuehlbauer** [comment]
@takluyver Did see your comment just after I sent mine. I removed the `MappingHDF5` inheritance and everything seems to run smoothly (tox-ing). Should I just update this PR?

**Comment by takluyver** [comment]
I'd be inclined to do that. Don't forget to add a [news entry](https://regro.github.io/rever-docs/news.html) as well.

I'll leave it a day or two in case anyone else chimes in with an argument in favour of keeping and fixing the mapping interface.

**Comment by tacaswell** [comment]
That the output of `__iter__` can not got into the input to `__getitem__` is a pretty strong indication that this was not intended to be a maping.

**Pull request merged**
