### PR TITLE
DOC: 2.7.1 release notes

### PR DESCRIPTION
**Pull request by tacaswell**
attn @aragilar

### CODE REVIEW

**Comment by aragilar** [comment]
Added the "What's New" with #903 and #904 (2.7.1 was just those changes right, with maybe #842?). If we're making the current state of master 2.7.1, I'll go through the history and add them to the what's new.

**Comment by tacaswell** [comment]
I was going to cut it off of master, I did go through and write down everything, but seem to have not commited that file...I'll do that when I get home today.

**Comment by tacaswell** [comment]
attn @aragilar

**Comment by aragilar** [comment]
@tacaswell All merged, sorry I missed your earlier message.

**Comment by tacaswell** [comment]
No worries!

**Pull request merged**
