### PR TITLE
Get processor architecture at compile time

### LINKED ISSUE #1079: Importing h5py before mpi4py causes OpenMPI warnings
**Version information:**
- h5py    2.8.0
- HDF5    1.10.2
- Python  3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
- [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
- sys.platform    linux
- sys.maxsize     9223372036854775807
- numpy   1.15.0

My 'problem' is really simple: Whenever I execute a script that imports h5py before mpi4py in MPI (on a cluster running UNIX), I get the following warning:
```
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[22007,1],2] (PID 94545)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
```

And, yes, this script can be as simple as:
```
import h5py
from mpi4py import MPI
```
and running such a script with `mpiexec -n 4 python -m mpi4py test.py`.

I do not get this warning whenever I import mpi4py before h5py.
I have seen this warning appear on multiple different clusters that use OpenMPI (it does not appear when using MPICH2, for example).

Now, I know that this warning can be prevented by simply importing mpi4py before h5py (or not using OpenMPI), and I have actually never seen any damage being caused or anything, but I simply wanted to raise this issue in case it is a sign of a problem.

Anybody else has ever seen a similar warning before?

### PR DESCRIPTION
**Pull request by takluyver**
Avoids the platform module running a subprocess during import.

Hopefully this might fix #1079.

### CODE REVIEW

**Comment by takluyver** [comment]
Tests are passing. I think this is a good idea in general (avoiding work at import time), but it would be good if someone who's been seeing the MPI warnings can see if this fixes them.

**Comment by jonaslb** [comment]
Fixes it for me! :)

**Comment by takluyver** [comment]
Thanks! I'll merge this tomorrow if no-one spots any problems or wants more time to look at it.

**Comment by kif** [comment]
Is cross-compilation an issue ?
Beside this it passes on ppc64le

**Comment by takluyver** [comment]
I wouldn't even know how to go about cross-compiling it. Is there any likely scenario where you'd cross-compile to or from PowerPC? If we don't know of anyone who needs that, I'd say we don't need to worry about it.

**Comment by aragilar** [comment]
Cross-compiling python extensions isn't a thing as far as I know (cross-compiling cpython itself seems quite difficult - http://www.trevorbowen.com/2013/10/07/cross-compiling-python-2-7-5-for-embedded-linux/). I think if this works on x86 and ppc64le, as this is only used to check for the PowerPC float detection issue, then this should be fine to merge, so I'm going to go ahead and do that.

**Comment by aragilar** [comment]
Thanks @takluyver for fixing this.

**Comment by takluyver** [comment]
The underlying issue - that `platform.machine()` launches an unnecessary subprocess - appears to have also been fixed for Python 3.9 (https://github.com/python/cpython/pull/12239 ).

**Pull request merged**
