### PR TITLE
Add open_file_image for opening a file from an image

### PR DESCRIPTION
**Pull request by mdietz94**
Adds access to H5LTopen_file_image from the low level interface. This will allow opening files from byte arrays without creating an empty file, as opening a new file and then calling set_file_image would.

### CODE REVIEW

**Comment by tacaswell** [comment]
How does this relate to #1061 ?

**Comment by mdietz94** [comment]
My understanding of #1061 is that it allows users to construct files with file-like objects instead of paths, whereas this change would allow users to construct files from byte arrays directly using the image api.

It would be possible to rewrite this change in terms of the other, by creating a fake file over the byte array, or vice versa by reading out the file and then using this api, but I think using the low level interface more directly should be more user friendly and predictable, especially as this change will expose the remainder of the image api that was partially exposed by the existing get_file_image and set_file_image methods.

**Comment by mdietz94** [comment]
Friendly ping.

**Comment by aragilar** [comment]
I'm happy to merge this, given that it's exposing existing HDF5 functions. If #1061 can benefit from this in some way, all the better.

**Comment by mdietz94** [comment]
Great! Thanks!

**Comment by mdietz94** [comment]
@aragilar ?

**Comment by aragilar** [comment]
Merging, @mdietz94 thanks for this!

**Comment by mdietz94** [comment]
Great, thanks so much!

**Pull request merged**
