### PR TITLE
Prepare to release 3.11.0

### PR DESCRIPTION
**Pull request by takluyver**
rever steps `version_bump` and `changelog`, followed by manual cleanup.

### CODE REVIEW

**Comment by ajelenak** [comment]
When is the release date? Would it be possible to add support for libhdf5-1.14.4, due out later next week?

**Comment by takluyver** [comment]
There isn't a set date, but Numpy 2.0 is coming quite soon, and I imagine there are downstream packages that would like to test with Numpy 2.0rc1 and h5py before Numpy 2 is final. So there is some time pressure.

Do you know how much effort supporting HDF5 1.14.4 is likely to be? Is #2403 likely to be the only issue?

**Comment by ajelenak** [comment]
There's native (libhdf5) support for float16 datatype. I have branch and will make a PR so the changes can be discussed.

**Comment by takluyver** [comment]
Please do! My instinct, though, is that cutting over from our added float16 type might be thorny enough that we want to get 3.11 out the door before tackling that. Let's see what the PR looks like, though.

**Comment by ajelenak** [comment]
See #2406.

**Comment by takluyver** [comment]
3.11 is out on PyPI now.

Unfortunately we don't have Linux aarch64 wheels at the moment. These were built on Travis CI using their 'partner queues', where ARM & IBM provide their respective CPU architectures for open source projects to use. Travis builds haven't been launching for a few months; I asked Travis support about this a few days ago, but so far there's no movement. Maybe this will come back for a future release, maybe we'll move it to another CI provider, or maybe it's just more than we have room to support. :shrug:

**Comment by lpsinger** [comment]
cibuildwheel provides instructions for how to do aarch64 builds under qemu emulation on free tier GitHub Actions.

**Pull request merged**
