### PR TITLE
Try building with numpy 2.0 rc1

### PR DESCRIPTION
**Pull request by takluyver**
See discussion on #2353.

### CODE REVIEW

**Comment by takluyver** [comment]
Numpy 2.0 requires Python >= 3.9, whereas we're still testing against 3.8. So for now I've made it conditional: it continues using `oldest-supported-numpy` to build on Python 3.8.

We can discuss dropping Python 3.8 as a separate question. The [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) recommendation is to drop it later this month, though I tend to err on the cautious side with old Python versions, not least as we're still using 3.8 in some places at XFEL.

**Comment by takluyver** [comment]
Looks like we've got some issues on Windows, mostly similar to:

```
>           assert normalized_dset_dtype == normalized_arr_dtype, \
                "Dtype mismatch (%s vs %s)%s" % (normalized_dset_dtype, normalized_dset_dtype, message)
E           AssertionError: Dtype mismatch (int64 vs int64)
```

**Comment by takluyver** [comment]
Ah, I see there's a bug in the helper function that makes the message less than helpful.

**Comment by takluyver** [comment]
That seems to be working; I'll merge in another day or so if there are no objections.

**Comment by aragilar** [comment]
Looks good to me, and agree on keeping python 3.8 supported for now.

**Pull request merged**
