### PR TITLE
Build & test wheels on Python 3.12

### LINKED ISSUE #2310: cp312 wheels
Now that numpy 1.26 has been released, is there a timeline for releasing cp312 wheels for h5py?

### PR DESCRIPTION
**Pull request by takluyver**
Closes #2310

### CODE REVIEW

**Comment by takluyver** [comment]
Good, that seems to work. I was a bit worried that we might have to fix Cython 3 compatibility (#2268) before we could support 3.12.

**Comment by aragilar** [comment]
We probably want to add 3.12 to tox as well. We don't include classifiers for Python versions, so we don't need to update them.

**Comment by takluyver** [comment]
Thanks, good point. I've added the tox config now.

**Comment by tacaswell** [comment]
Should we backport this to a branch one commit past the last tag to avoid having to do a release to publish 312 wheels?

Insert my normal complaints about the issues of bundling the binary artifact generation logic into the project source code.

**Review by tacaswell — APPROVED** [review]

**Pull request merged**
