### PR TITLE
Cimport numpy from cython instead of maintaining a local binding

### PR DESCRIPTION
**Pull request by kif**
Some more work is probably needed but it will require deeper hack. This is hence the superficial layer.
Related to #1367

### CODE REVIEW

**Comment by aragilar** [comment]
@kif This will need a rebase. What's stopping us from dropping the rest of the Python.h stuff?

**Comment by kif** [comment]
On Sun, 13 Oct 2019 00:51:57 -0700
James Tocknell <notifications@github.com> wrote:

> @kif This will need a rebase. 

OK, I'll do it.

> What's stopping us from dropping the rest of the Python.h stuff?

Thomas K. wanted multiple small PR which are easier to review for you.
This is why I stopped here (for this first PR)
Other are likely coming after that.

**Comment by aragilar** [comment]
@kif Ah, cool, that makes sense. If there's anything cython doesn't expose, it's probably worth checking with them if there's a reason, in case there are APIs we shouldn't be using.

**Comment by kif** [comment]
After the rebase, I have a seg-fault on the tests :(

Concerning non exposed function, the numpy/__init__.pxd states that those functions are commented out because they are stealing dtype. but I did not yet fully understand the meaning of:
``` # Functions taking dtype and returning object/ndarray are disabled
    # for now as they steal dtype references. I'm conservative and disable
    # more than is probably needed until it can be checked further.
``` commented by Dag from cython.

**Comment by takluyver** [comment]
Thanks @kif, this looks like a good step forwards. I don't fully grasp all of the Cython stuff, but the tests on CI seem to be passing (the failure shown is a problem with uploading coverage data - #1398).

Did you fix the segfault you were seeing?

**Comment by kif** [comment]
I believe the bug is in the azure pipeline ... codecov passed directly but not via azure where it tries to upload some data.

**Comment by kif** [comment]
I can confirm the seg-fault was an issue on my rebase. I believe it is safe for merging.

**Comment by takluyver** [comment]
Thanks @kif. I'll give it a day or so in case the other maintainers around the world want to take a look, then I'm happy to merge it.

**Comment by tacaswell** [comment]
Do we need to keep numpy.pxd around for back-compatibility reasons?

**Comment by kif** [comment]
On Mon, 14 Oct 2019 08:50:35 -0700
Thomas A Caswell <notifications@github.com> wrote:

> Do we need to keep numpy.pxd around for back-compatibility reasons?

For now yes ... but we are working on this. It will be part of another
which may be more intruisive.

h5t still relies on the dtype class defined in h5py and cannot use the
one from cython. I suspect there is a mix between import and cimport.
Work in ongoing but with Thomas K. we agreed to split this large
refactoring in smaller part to create an adiabatic pathway (i.e.
reversible).

Cheers,

Jerome

**Pull request merged**
