### PR TITLE
initial release guide

### PR DESCRIPTION
**Pull request by scopatz**
for #1300 
Also adds package signing for PyPI on rever v0.4.2+

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks!

Should we discuss package signing? I think we either need to commit to taking it seriously - i.e. establishing, documenting and maintaining a set of keys which people should trust to make h5py releases - or scrap package signing. If we're not doing it properly, it's a complete waste of time, and worse, it gives an impression of security that doesn't exist.

**Comment by takluyver** [comment]
I don't bother with package signing on any other project I release, so that's definitely my preference. My experience is that people only complain when a project that previously did sign releases stops, not when a project never started signing, so I don't think it's really important.

**Comment by scopatz** [comment]
this passes CI now

**Comment by aragilar** [comment]
The only thing preventing this from be merged seems to be the addition of signing to rever (which is discussed in #1299), I suggest leaving the signing (or non-signing) to a different PR.

**Comment by scopatz** [comment]
@aragilar - would you like me to remove that one line then?

**Comment by aragilar** [comment]
@scopatz Yep, we can argue about signing vs not signing in #1299, no need to leave this waiting for that. Also, can rever upload to test.pypi.org and/or do dry runs of releases, as that might be worth adding to the CI, so that we can quickly catch issues with the release process?

**Comment by scopatz** [comment]
@aragilar done!

> Also, can rever upload to test.pypi.org and/or do dry runs of releases

That is a great idea! There is probably a way to do it, already, but adding that to the `rever check` for the pypi activity would be ideal.  Can you open an issue on rever for this please?

**Pull request merged**
