### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by claweyenuk**
Added license from http://docs.h5py.org/en/stable/licenses.html

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! Can we use the canonical format of the BSD 3-clause license (which for example uses 1, 2, 3 rather than a, b, c): https://choosealicense.com/licenses/bsd-3-clause/

**Comment by claweyenuk** [comment]
Done (there were some other minor changes I copied from that license too (copyright owner->copyright holder, and the like)

**Comment by tacaswell** [comment]
I prefer that @andrewcollette sign off on this as it is (trivially) changing the text of the license.

**Comment by andrewcollette** [comment]
I don’t have a problem with it!  I would suggest, though, that the URL in the license be removed or pointed to h5py.org.

**Comment by claweyenuk** [comment]
Sure, it's a quick change, and I even have the terminal open still where I made the changes.  Any preference between the different URLs?

https://www.h5py.org/
http://www.h5py.org/
http://h5py.org/

(I notice https://h5py.org/ doesn't work which I've seen with github sites before I think b/c SSL certs not matching)

**Comment by andrewcollette** [comment]
Actually I’d say just remove it at this point since those details are in flux.

**Comment by takluyver** [comment]
Thanks!

**Pull request merged**
