### PR TITLE
Document in strings.rst usage of special_dtype(vlen=str)

### PR DESCRIPTION
**Pull request by doronbehar**
I have been using the example I documented here for a while now. Felt it was missing. I had to learn this from the question [here](https://stackoverflow.com/questions/68500454/can-i-use-h5py-to-write-strings-to-an-hdf5-file-in-one-line-rather-than-looping).

### CODE REVIEW

**Comment by aragilar** [comment]
Rather than `h5py.special_dtype(vlen=str)` (which is oldish and somewhat implicit about what it means, though I don't think we'll drop support for it), you should use `h5py.string_dtype(encoding='utf-8', length=None)` (or, since those are the default values `h5py.string_dtype()`).

**Comment by doronbehar** [comment]
Hmm I wonder how I missed that back then... The docs indeed mention `[string_dtype](https://docs.h5py.org/en/stable/special.html#h5py.string_dtype)`, but they don't tell you to use that for datasets, and only gives examples for attributes. I pushed something.

**Comment by takluyver** [comment]
Thanks! I think this could benefit from an example. But it's a fairly confusing topic, because of all the different possible string types, and I think it needs careful presentation to avoid muddying the waters. So I hope you won't mind if I open a new PR reworking this example to show the different possibilities.

**Comment by takluyver** [comment]
I've tried to do that in #2424.

**Comment by takluyver** [comment]
I'm going to close this as I've merged #2424. Thanks!

**Comment by doronbehar** [comment]
Thank you for your help.

**Pull request closed without merging**
