### PR TITLE
Fix non-linux build.

### LINKED ISSUE #1237: AttributeError on import when building from source
To assist reproducing bugs, please include the following:
 * Operating System: macOS 10.14
 * Python version: 3.7.2
 * Where Python was acquired: Anaconda
 * h5py version (e.g. 2.6): f5463ad632510a39bd04f895a60784985c8ddbfa
 * HDF5 version (e.g. 1.8.17): 1.10
 * The full traceback/stack trace shown (if it appears):

```
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hameerabbasi/Quansight/h5py/h5py/__init__.py", line 49, in <module>
    from ._hl.files import (
  File "/Users/hameerabbasi/Quansight/h5py/h5py/_hl/files.py", line 41, in <module>
    libver_dict.update({'v108': h5f.LIBVER_V18, 'v110': h5f.LIBVER_V110})
AttributeError: module 'h5py.h5f' has no attribute 'LIBVER_V18'
```

### PR DESCRIPTION
**Pull request by hameerabbasi**
Fixes #1237.

### CODE REVIEW

**Comment by aragilar** [comment]
@hameerabbasi Can you move the OS checking to https://github.com/h5py/h5py/pull/1240/files#diff-98ec0cb2149a0c4f74a0e18b57e345dcL206 so that we only check the OS in one place (maybe use a variable such as `fallback_path`, and have `if path is None: path = fallback_path`)?

**Comment by hameerabbasi** [comment]
> @hameerabbasi Can you move the OS checking to https://github.com/h5py/h5py/pull/1240/files#diff-98ec0cb2149a0c4f74a0e18b57e345dcL206 so that we only check the OS in one place (maybe use a variable such as fallback_path, and have if path is None: path = fallback_path)?

Done!

**Comment by takluyver** [comment]
This looks like a sensible change to me. I'll leave it for a while to get input from people who might be more familiar with other platforms, but I'm happy to merge it for 2.10.

**Comment by scopatz** [comment]
Yep, this looks very reasonable to me too.  Thanks @hameerabbasi!

**Comment by takluyver** [comment]
OK, that's three of us agreeing on it. Good enough for me. :-)

**Pull request merged**
