### PR TITLE
FIX: hide mpi imports until as late as possible

### LINKED ISSUE #1081: import h5py initializes mpi prematurely
importing h5py inits mpi which then starts orted:

```sh
$ python -c 'import h5py, os; os.system("ps -x|grep orted")'
12485 pts/6    Sl+    0:00 python -c import h5py, os; os.system("ps -x|grep orted")
12530 ?        Ssl    0:00 orted --hnp --set-sid --report-uri 11 --singleton-died-pipe 12 -mca state_novm_select 1
12543 pts/6    S+     0:00 sh -c ps -x|grep orted
12545 pts/6    S+     0:00 grep orted
```

orted inherits the parent's open files so the open sockets are a mess:

```sh
$ lsof -i -P
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sirepo    12630 vagrant    3u  IPv4 379187      0t0  TCP *:8000 (LISTEN)
sirepo    12630 vagrant   24u  IPv4 379177      0t0  TCP *:1024 (LISTEN)
orted     12678 vagrant   16u  IPv4 378655      0t0  TCP *:51099 (LISTEN)
python2.7 12688 vagrant    3u  IPv4 379187      0t0  TCP *:8000 (LISTEN)
python2.7 12688 vagrant    4u  IPv4 379187      0t0  TCP *:8000 (LISTEN)
python2.7 12688 vagrant   24u  IPv4 379177      0t0  TCP *:1024 (LISTEN)
python2.7 12688 vagrant   30u  IPv4 379191      0t0  TCP *:1025 (LISTEN)
orted     12692 vagrant    3u  IPv4 379187      0t0  TCP *:8000 (LISTEN)
orted     12692 vagrant   19u  IPv4 378672      0t0  TCP *:39617 (LISTEN)
orted     12692 vagrant   24u  IPv4 379177      0t0  TCP *:1024 (LISTEN)
```

To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
Fedora 27
 * Python version (e.g. 2.7, 3.5)
2.7.14
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
pyenv
 * h5py version (e.g. 2.6)
2.8.0
 * HDF5 version (e.g. 1.8.17)
hdf5-openmpi-static-1.8.18-11.fc27.x86_64
hdf5-1.8.18-11.fc27.x86_64
hdf5-openmpi-devel-1.8.18-11.fc27.x86_64
hdf5-devel-1.8.18-11.fc27.x86_64
hdf5-openmpi-1.8.18-11.fc27.x86_64
 * The full traceback/stack trace shown (if it appears)
n/a

python -c 'import h5py; print(h5py.version.info)'
```
python -c 'import h5py; print(h5py.version.info)'
Summary of the h5py configuration
---------------------------------

h5py    2.8.0
HDF5    1.8.18
Python  2.7.14 (default, Jul  7 2018, 02:04:27)
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
sys.platform    linux2
sys.maxsize     9223372036854775807
numpy   1.14.5
```
where `python` should be substituted for the path to python used to install
`h5py` with.

### PR DESCRIPTION
**Pull request by tacaswell**
This may help all of the mpi order-related issues.

closes #1081

### CODE REVIEW

**Comment by tacaswell** [comment]
xref https://github.com/h5py/h5py/issues/1095 https://github.com/h5py/h5py/issues/1093 https://github.com/h5py/h5py/issues/1081 https://github.com/h5py/h5py/issues/1079

attn @tmaric @robnagler @1313e does this fix any of your problems?

**Comment by robnagler** [comment]
Yes, fixes the problem. Thanks!

**Comment by tacaswell** [comment]
The thing I find confusing is that the offending import was added in 2013 (6a626ee04c975380f0d7220df1ee4569469586c5), but these problems have only begun to be reported recently.  Did mpi4py change something about how it initializes it's self?

**Comment by robnagler** [comment]
I think we've had these problems "all along", or at least since 2.7.1: https://github.com/radiasoft/sirepo/issues/1151

**Comment by tacaswell** [comment]
I would have expected to see these issues going back 4 years, that issue is only 6mo's ago ;)

**Comment by tacaswell** [comment]
@1313e can you try going back to mpi4py v2.0.0?  I wonder if they change something about what they do on import?

**Comment by 1313e** [comment]
@tacaswell I just performed the test using mpi4py v2.0.0 and I still get the same results as mentioned above: OpenMPI warnings when importing mpi4py before h5py, but not when I import h5py before mpi4py (happens for both h5py v2.8.0 and your branch).
I am really confused now as to why the situation for that warning is swapped.

**Comment by 1313e** [comment]
@tacaswell Nothing happens, no warnings.
Although (please correct me if I am wrong), importing the same module twice has no effect due to the way that the Python importer works, right?

**Comment by tacaswell** [comment]
I also expect there to be no effect from importing a module twice, as it should go just get the already imported module from `sys.modules`, but it seems that the second import of `mpi4py` when one of the imports is inside of h5py causes the warnings so something fishy is happening!

I don't really know enough MPI to understand https://mpi4py.readthedocs.io/en/stable/mpi4py.run.html
but the "At import time, mpi4py initializes the MPI execution environment calling MPI_Init_thread()" seems suspicious to me.  I have the sense that this is something you should not do twice.  Could both mpi4py and the underlying hdf5 library are both trying to be helpful and messing with each other?

Again, I know so little about MPI, do you have to re-compile to switch between OppenMPI and MPICH2?   Could there be a conflict between the version mpi4py / h5py / hdf5 are set up for?

Do we have any idea what is doing the forking (I assume mpiexec)?

**Comment by 1313e** [comment]
@tacaswell It might be mpi4py, but I only have this problem when using OpenMPI. Using MPICH2 does not cause this problem (and yes, mpi4py needs to be recompiled in order to switch between MPI distributions).
To be honest, that mpi4py automatically initializes the MPI environment has caused me enough headaches already. However, I do know that attempting to initialize the MPI environment when it is already initialized will not work. If you try to initialize it twice, the program itself will simply crash (one can easily check this by executing `from mpi4py import MPI` and `MPI.Init()`).
I also just checked what happens when I import mpi4py before h5py in an iPython console (so, not executed in an MPI environment) and I get the same warnings.

**Comment by takluyver** [comment]
There appear to be several different issues:

- #1081 says importing h5py is doing too much MPI initialisation (possibly by importing mpi4py?)
- #1079 is a fork warning with importing mpi4py after h5py
- #1093, #1095, [this mailing list post](https://groups.google.com/forum/#!topic/h5py/AZRc35i7mGg) and @1313e's comments in this post all seem to refer to seeing the fork warning when importing mpi4py before h5py.

I'm still trying to make head or tail of this.

**Comment by takluyver** [comment]
People who can get the fork warning reliably: can you try using [strace](https://linux.die.net/man/1/strace) to look for fork and exec* system calls and try to work out what is attempting to start a subprocess?

**Comment by 1313e** [comment]
@takluyver I can get that fork warning reliably, but using strace does not really give anything.
`fork` never occurs in the entire output and `exec` only once in the form of `mpiexec` (which is my own command).

**Comment by takluyver** [comment]
That's curious. I had a look at the OpenMPI source code, and the warning seems to be hooked up by a handler registered with [pthread_atfork](http://man7.org/linux/man-pages/man3/pthread_atfork.3p.html), which is meant to register handlers to be called on `fork()`. I see only one reference to the message, and no indication that the fork handlers fire in any situation other than a fork. :confused:

**Comment by takluyver** [comment]
In any case, I think delaying the import of mpi4py until the mpio driver is used makes sense. It appears to solve at least one of the issues related to MPI (#1081), and it doesn't appear to make other issues worse. So I suggest we merge this change and continue to investigate the causes of the fork warning separately.

**Comment by 1313e** [comment]
@takluyver Sounds like a good idea.

**Comment by leofang** [comment]
I wandered to this page and wonder if the conflicts between `h5py` and `mpi4py` has been fully resolved. Our code also encountered the similar situation if `h5py` is built against an MPI-enabled hdf5. Our solution is to not initialize MPI and let `h5py` do the job:

```Python
import mpi4py
mpi4py.rc.initialize = False # undocumented switch
from mpi4py import MPI
assert not MPI.Is_initialized()
import h5py # must be loaded after mpi4py, or it'd initialize MPI if parallel HDF5 is built!
# ...and do the work
```

This, together with mpio, seems to work for us. In this case we used `mpi4py` v3.0.0 and `h5py` v2.7.1.

**Comment by tacaswell** [comment]
@leofang can you try this with master branch?

**Comment by leofang** [comment]
@tacaswell sorry I missed the notification. I just updated my earlier comment slightly. The code snippet above works for both h5py v2.8.0 and the current master branch.

I want to add that we never saw error messages as reported in #1079, and I'm wondering if the linked issues are related to how MPI, HDF5, etc are built and not to h5py itself. 

The problem we encountered is that there's a certain initialization order when using MPI together with (CUDA) GPU, and importing a parallel hdf5/h5py initialized MPI prematurely and thus messed up this order, as observed in #1081 and also revealed in the script below (tested with h5py v2.8.0 and master):
```python
import h5py # MPI is already initialized here...
import mpi4py
mpi4py.rc.initialize = False # undocumented switch
from mpi4py import MPI

# MPI.Is_initialized() is supposed to be False given the switch is turned off,
# but surprisingly it's True because h5py is imported first!
assert MPI.Is_initialized()
``` 
I would therefore suggest to load h5py always after mpi4py.

**Comment by 1313e** [comment]
I personally still have the feeling that this is something that occurs only when using OpenMPI (since it does not happen with MPICH2 or Microsoft MPI), which would not surprise me given that I have found several other 'problems' with it as well.
But, since `h5py` is the only package that does this with OpenMPI (using other packages that use `mpi4py` do not raise that warning), I figured it had something to do with `h5py`.
I do not know how however, so do not ask me that. :)

**Comment by 1313e** [comment]
> Just a bit of digression: I have no idea M$ has its own MPI!

It is the only MPI implementation that one can actually use on Windows.

**Comment by DTHaydon** [comment]
I have a MPI HDF5 library compiled.

When I import h5py built from this library:

    import h5py
    # ---------- or ----------
    import h5py
    from mpi4py import MPI
    # ---------- or ----------
    from mpi4py import MPI
    import h5py
    # ---------- or ----------
    import mpi4py

    # combinations of the following
    mpi4py.rc.initialize = False
    mpi4py.rc.threads = False
    mpi4py.rc.thread_level = "single"

    from mpi4py import MPI
    import h5py
 
I always get the warning:

> A process has executed an operation involving a call to the
> "fork()" system call to create a child process.  Open MPI is currently
> operating in a condition that could result in memory corruption or
> other system errors; your job may hang, crash, or produce silent
> data corruption.  The use of fork() (or system() or other calls that
> create child processes) is strongly discouraged.

However I compiled and ran the C code example from:
https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/examples/ph5example.c
(which creates and writes HDF5 files in parallel)
using the same MPI HDF5 library that I built h5py and there is no warning.

Do we know if it's something `mpi4py` is doing of `h5py`?

------------
h5py 2.9.0
mpi4py 3.0.0
HDF5 1.10.4
Open MPI 3.0.0
Linux 3.10.0-693.5.2.el7.x86_64 x86_64

**Comment by leofang** [comment]
Hi @DTHaydon, not sure if this would help, but could you please try newer version of Open MPI, say 3.1.3? According to its [changelog](https://raw.githubusercontent.com/open-mpi/ompi/v4.0.x/NEWS), in 3.0.1 they
> Fix a number of issues in MPI I/O found by the HDF5 test suite.
Unfortunately you'd also need to rebuild everything (HDF5, mpi4py, h5py) to ensure they all work on top of the new version I think.

Also, for all affected users, could you please report your Open MPI version? I don't find *any* in the linked issues. Thanks.

**Comment by DTHaydon** [comment]
Unfortunately this is on a university cluster, so I don't have so much control of what MPI version I'm using.
However, if the Open MPI version is the issue, I would expect the C code to also give the same fork() warning.

**Pull request merged**
