### PR TITLE
Refactor selection code

### PR DESCRIPTION
**Pull request by takluyver**
I'm not 100% convinced by this, but I've been working on it on and off for a few days, and I'd like a reality check.

This is aimed at read performance, building on my work in #1402. I noticed that after that PR, about 1/3 of the time taken for small reads was in the selection code (15 µs per small read). Taking a small slice of a numpy array takes about 300 ns, so it seems like there's room for improvement. My thinking was to prioritise the 'normal' cases - standard dataset indexing and slicing - over more advanced things.

**The numbers**: this speeds up selection by something like 30-40%, and small reads by about 10% (~55 µs -> 49 µs).

As far as I can tell, this comes from two main sources:

- Avoiding repeated iteration over the indexing arguments - even though there aren't many, Python's iterator protocol has some overhead.
- Avoiding unnecessary HDF5 calls - don't call `select_all()` if it's not needed, and reuse & modify a cached SpaceID for repeated reads from the same dataset (with the same cache rules as for shape and size, from PR #1402).

I don't think this actually introduces a lot of extra complexity, but it does make the code longer and probably uglier. And the performance gains, while not nothing, are not the kind of massive leap I was hoping for. So maybe the best thing is to consider this a learning exercise and hope I come up with something better in the future.

----

asv graph (#1403):

Screenshot from 2019-10-28 14-24-21

### CODE REVIEW

**Comment by takluyver** [comment]
Although, in its favour: I think I fixed #993 along the way. But that's feasible without the rest of the changes if we don't merge it.

**Comment by scopatz** [comment]
Selection code is always pretty verbose.  I am totally in favor of this. It defintiely seems worth it to me

**Comment by takluyver** [comment]
I now prefer my approach in #1428 - whereas this PR tries to speed up the fully general read pathway implemented largely in Python, that one makes a fast path in Cython for typical reads, and can be much faster. Maybe it's possible to expand that to the point where we don't need the hyperslab-selection code in Python anyway.

**Comment by takluyver** [comment]
Closing this, as #1428 achieved a much bigger speedup. I'm hoping to look at using that code in a greater range of situations (without compromising its performance).

**Pull request closed without merging**
