### PR TITLE
Use 'twine check' to check readme

### PR DESCRIPTION
**Pull request by dota17**
Fix https://github.com/h5py/h5py/issues/1653

cc: @takluyver

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! It's just the ever-mystifying authors check complaining now:

```
'chenguopingdota@163.com' does not have 'Chenguoping' listed! Please add the name to 'chenguopingdota@163.com' in '.authors.yml'. For example:

- name: Chenguoping
  email: chenguopingdota@163.com

Or add an alias:

- name: Some Body Else
  email: chenguopingdota@163.com
  aliases:
    - Chenguoping
```

**Comment by dota17** [comment]
Yes, I see it, but I have no idea why it complains again 😅

**Comment by takluyver** [comment]
@scopatz is this case sensitive? It's asking for 'Chenguoping', althought 'chenguoping' is already listed as an alias.

**Comment by takluyver** [comment]
For that matter, what does it use aliases for? It seems like the email address in the commit should be enough to identify the author, and we can use the `name:` field in attribution messages.

**Comment by dota17** [comment]
I tried to change email/name in `.author.yml`, or change the local git configuration by `git config --global user.name/user.email`, none of them successed.

**Comment by takluyver** [comment]
I don't exactly know, but we need to make it pass somehow before we can merge the PR, otherwise it will fail for everyone.

**Comment by dota17** [comment]
OK, thanks! The static check turns out green now.

**Comment by takluyver** [comment]
Super. This is ready to go.

**Pull request merged**
