### PR TITLE
CI: Add testing of HDF5 develop branch

### PR DESCRIPTION
**Pull request by aragilar**
This adds the develop branch of HDF5 to travis (with `allow_failures`). We could add more branches, but I'm guessing what we really need is some way of notifying the HDF5 group on failure of these and similar tests (do we know what CI system they are using?).

### CODE REVIEW

**Comment by aragilar** [comment]
This looks like it's found a bug, somewhere we're returning `v112` where we should be returning `latest`.

**Comment by takluyver** [comment]
I feel like `allow_failures` jobs aren't super useful, because we so rarely look at them.

Would it be better to have a separate repo/branch which runs the tests on a schedule (weekly?) with h5py master and the HDF5 develop branch? Then it could send email notifications on failure, without marking all PRs as failing if something gets broken. Hopefully there would also be a button to manually trigger a test run when you think you've fixed a problem.

**Comment by takluyver** [comment]
Azure has [scheduled triggers](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#scheduled-triggers), so that plan also wouldn't be tied to Travis.

**Comment by aragilar** [comment]
@takluyver Maybe I missing something, but I can't see any way of filtering jobs on azure (e.g. only run these job at this time). We could use circle ci, and leave it solely for running a weekly test between h5py and HDF5 (testing against develop and each of the series branches), and there's less conditional logic inside the azure config. I'm happy to remove the travis version, I went with putting it on travis because I find it easier and faster to get something working on travis than azure.

**Comment by takluyver** [comment]
I was just thinking of having a separate repo or branch with its own CI configuration for scheduled tests.

**Comment by aragilar** [comment]
I'm going to close this, creating a repository which does daily rebuilds against the in-dev HDF5 is probably a better way forward (as suggested by @takluyver), and will mean that we can also test against released versions of h5py also. I won't delete the branch, in case people want to use the code as a basis for the new repository (hopefully future James will notice this message and not delete it by mistake...).

**Pull request closed without merging**
