### PR TITLE
Prepare to release 3.12

### PR DESCRIPTION
**Pull request by takluyver**
Rever steps `version_bump` & `changelog`, then manual writing and cleanup.

This release will be pretty light on features, it's mostly bugfixes and cleanups. We didn't do a great job of reminding people to write release notes in PRs.

@neutrinoceros am I right that we're ready to upload wheels for Python 3.13? I see NumPy already has.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
yes, cp313 (GIL flavor) wheels are go.
cp313t wheels are another story, but it doesn't seem blocking to me.

**Review by neutrinoceros — APPROVED** [review]

**Comment by takluyver** [comment]
Thanks! Yes, I don't want to block on free-threading wheels. I've made it explicit in the release notes that that's not supported yet.

**Comment by takluyver** [comment]
h5py 3.12.0 is on PyPI & Github releases now.

**Comment by robomics** [comment]
The new release may have introduced a regression on Windows, see https://github.com/h5py/h5py/issues/2505.

**Comment by takluyver** [comment]
Thanks for the heads up!

**Pull request merged**
