### PR TITLE
Add HDF5 Virtual Dataset API

### PR DESCRIPTION
**Pull request by ajelenak-thg**
Virtual Dataset is a new feature in the upcoming version 1.10 of the HDF5 library. More information about it is on The HDF Group's [website](https://www.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesVirtualDatasetDocs.html).

This pull request adds the Virtual Dataset's HDF5 [API](https://www.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesVirtualDatasetDocs.html#Hdf5LibraryApis) to h5py's low-level interface.

To build this version of h5py requires a development version of HDF5 library and autoconf, automake, and libtool tools:

```sh
$ svn co https://svn.hdfgroup.uiuc.edu/hdf5/branches/hdf5_1_10_alpha/
$ cd hdf5_1_10_alpha
$ . ./autogen.sh
$ ./configure --prefix=<...>
$ make -j8
$ make check -j8
$ make install
```

Finish by following h5py's [instructions](http://docs.h5py.org/en/latest/build.html#custom-installation) for custom installation.

### CODE REVIEW

**Comment by ulrikpedersen** [comment]
:+1: 

This is great. We have tried it out in a small VDS example (in combination with SWMR) and it worked.

Looking forward to a high-level VDS interface, docs and demo :wink: 

Maintainers: anything required before this can be merged?

/cc @ajgdls

**Comment by andrewcollette** [comment]
Looks good to me.  Although there are no tests I'm inclined to merge it so we can get feedback from people testing the new versions of HDF5.  @ajelenak-thg, we may refer some of that feedback to you.

**Comment by thisisjl** [comment]
Hi, is there any example code available for this? Thanks

**Comment by aragilar** [comment]
Currently no, although the low-level API will most likely match the examples given in the HDF5 documentation. There is work going on in #809 to add a high-level interface.

**Comment by thisisjl** [comment]
Thank you @aragilar for your quick reply.
I am pretty new to h5py, so I do not know how I could use the low-level API, are there examples for it?
I suppose [this example](https://github.com/aaron-parsons/h5py/blob/1e467f6db3df23688e90f44bde7558bde7173a5b/docs/vds.rst#using-the-vds-feature-from-h5py) is still the work in progress, or am I wrong?

**Pull request merged**
