### PR TITLE
Try uploading wheels from Travis to Github releases instead of anaconda.org

### PR DESCRIPTION
**Pull request by takluyver**
Another attempt at solving #2215.

I'll probably merge this later today and then create a tag so we can get the 3.8 wheels for aarch64.

### CODE REVIEW

**Comment by takluyver** [comment]
I briefly created a 'machine user' to own the token, but then realised that Github's new 'fine grained' tokens let me do the same thing without another account, so I've deleted `h5py-uploader` again. The 'fine grained' tokens can only be valid for a maximum of 1 year, though, which is annoying given that that's one or two releases for us.

**Comment by tacaswell** [comment]
I think we want to keep the upload to anaconda for nightlies though?

**Comment by takluyver** [comment]
Oh, sorry, I merged before seeing your comment. If the nightlies have been broken for 7 months without anyone noticing, I think that suggests it's a waste of effort to fix the upload. Hopefully the Travis deployment thing will work with less hassle.

**Comment by takluyver** [comment]
Of course we can always revisit that if we do want nightly aarch64 wheels. For now I'd just like to get them up for the release.

**Comment by takluyver** [comment]
This worked, but I had to switch back from the new 'fine grained' access token to a 'classic' token with much broader scope. I might create a machine user again to limit the scope to this one repo, or maybe Travis will add support for the fine-grained tokens.

**Comment by tacaswell** [comment]
> Of course we can always revisit that if we do want nightly aarch64 wheels. For now I'd just like to get them up for the release.

Oh, I missed that this was _only_ disabling aarch64 wheels.

**Comment by takluyver** [comment]
Yup, the x64 and ARM Mac wheels are produced on Azure, and available for download from there as 'artifacts'. They're automatically cleaned up a couple of weeks after the build.

**Pull request merged**
