### PR TITLE
FIX: Enable reading fixed-length UTF-8 strings

### PR DESCRIPTION
**Pull request by ajelenak-thg**
This adds a datatype conversion function that enables reading fixed-length UTF-8 strings into the h5py's chosen fixed-length null-padded ASCII string datatype as reported in issue #719.

The PR is meant to check whether this is the correct approach and, if not, what would be a more suitable one. The new conversion function avoids changing how h5py handles strings in any way and targets only fixed-length UTF-8 strings stored in HDF5 files.

### CODE REVIEW

**Comment by wavexx** [comment]
This would be relevant for #973 as well. Any reason it has not been accepted yet?

**Comment by aragilar** [comment]
@ajelenak-thg This fell off my todo list to review, sorry.

This feels like a hack which is going to bite us later. A better plan would be to do what's suggested in #973, which would be to create a proper "type" to handle utf-8 (via dtype's metadata), and if necessary, write a conversion function for that (once we can sensibly read and write fixed length strings of arbitrary encodings, then we can fix many of the issues listed at https://github.com/h5py/h5py/labels/string%2Funicode%20usage).

**Comment by t-b** [comment]
@ajelenak-thg Does #1132 make this PR obsolete?

**Comment by scopatz** [comment]
Looks like there are conflicts with master

**Comment by ajelenak-thg** [comment]
Withdrawing this PR because of #1132.

**Pull request closed without merging**
