### PR TITLE
Update windows type headers

### PR DESCRIPTION
**Pull request by aragilar**
This updates the windows interger headers for newer VS support.

### CODE REVIEW

**Comment by andreabedini** [comment]
Is this only precautionary or it fixes some problem with building on windows? (Just to understand)

**Comment by aragilar** [comment]
I needed this to get h5py to build on appveyor with python3, so this should fix problems, but it can wait until the appveyor work is ready to go (unless someone else has found this necessary to build on windows). I'll open an issue to track progress on getting appveyor to work.

**Comment by aragilar** [comment]
I've rebased this on top of the current master, to see if this gains us anything, and to make sure that this doesn't break anything.

**Comment by tacaswell** [comment]
should this be merged for #784 ?

**Comment by aragilar** [comment]
It doesn't need to be, it can wait till after we do the release. When I was experimenting on getting appveyor to work, I thought I did need this, but that may have been due to something else at the time.

**Comment by tacaswell** [comment]
Do we still need this, appevyor seems to be working with python3

**Comment by aragilar** [comment]
I'm happy to close this, there could have been a bug in something else which got fixed at some point, or something changed on appveyor, but given everything seems to work without these changes, I think closing this makes sense, we can always come back to this if need be.

**Pull request closed without merging**
