### PR TITLE
Fix default file mode in test as root

### PR DESCRIPTION
**Pull request by dota17**
Close: #1584
@takluyver  please take a look.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks. The CI failures is asking for your details to be in `.authors.yml` - can you check the message and add yourself?

**Comment by dota17** [comment]
> Thanks. The CI failures is asking for your details to be in `.authors.yml` - can you check the message and add yourself?

Done 😃

**Comment by takluyver** [comment]
I think it now wants `chenguoping` in your alias list. Sorry about this, I don't quite understand what rever needs, but we do need to get it passing, otherwise it will fail on master and all new PRs.

**Comment by dota17** [comment]
> I think it now wants `chenguoping` in your alias list. Sorry about this, I don't quite understand what rever needs, but we do need to get it passing, otherwise it will fail on master and all new PRs.

Ok, never mind, I understand. I will have a try again.

**Comment by takluyver** [comment]
It must want both your name on Github ('Chen') and the name you're committing as ('chenguoping').

@scopatz can we simplify our use of rever at all? It's nice to credit people by their preferred name, but I feel like it makes life unnecessarily difficult for people making a small contribution like this.

**Comment by dota17** [comment]
@takluyver well, finally, it passed! 😄 
I think we can add a note in `contributing.rst` to inform people who opened their first PR in h5py how to do this kind of thing.
and I'm willing to do this.

**Comment by takluyver** [comment]
Thanks for sticking with it! Yes, that would be very welcome if you want to improve that.

**Pull request merged**
