### PR TITLE
Update Travis CI to correctly use Ubuntu Trusty, plus additional CI/Testing improvements

### PR DESCRIPTION
**Pull request by aragilar**
This is a mix of different things:
 * HDF5 1.10 support (from #894)
 * Updating Travis to use Ubuntu Trusty (from #894) - Travis has now migrated to only Trusty, which is currently causing travis to fail.
 * A simplification of tox.ini (from #857)

### CODE REVIEW

**Comment by aragilar** [comment]
Closed and reopened to cycle CIs, there should be a better way...

**Comment by aragilar** [comment]
Appveyor appears to be playing up, the ci keeps getting stuck at removing a non-empty directory with rmtree...

**Comment by aragilar** [comment]
So the cause appears to be that shutil.rmtree doesn't always work on windows, which causes problems with removing the tmpdirs (see https://bugs.python.org/issue29982), I've dropped the non-WIndows support from get_hdf5.py (and so have moved it under the appveyor dir), and have wrapped the whole thing in an try..except with OSError, but if we still have problems, then I might just not use tmpdirs, and let the fact that this is only running on appveyor mean that I won't bother about cleanup code.

**Comment by tacaswell** [comment]
:tada: Congrats on defeating both CI services!

**Pull request merged**
