### PR TITLE
Enh add extra pt exposure function

### PR DESCRIPTION
**Pull request by tacaswell**
There are a couple more of these coming.

### CODE REVIEW

**Comment by scopatz** [comment]
"This needs a test" - @tacaswell

**Comment by andreabedini** [comment]
@scopatz @tacaswell how would you test this? I'd just merge it.

**Comment by tacaswell** [comment]
I would de-register / register one of the standard filters.

**Comment by andreabedini** [comment]
@tacaswell cool, good to leave a trail of our ideas :)

**Comment by takluyver** [comment]
@tacaswell do you think you'll have time to finish this up for 2.10, or shall I drop the milestone?

**Comment by takluyver** [comment]
Dropping the milestone for now because I want to push for a new release. We can always add it back to any milestone if someone finds time to finish it.

**Comment by scopatz** [comment]
See #1224

**Pull request closed without merging**
