### PR TITLE
ENH: Add missing py36 setting to tox

### PR DESCRIPTION
**Pull request by aragilar**
Minor update, missed 36 in numpy deps.

### CODE REVIEW

**Comment by tacaswell** [comment]
```
======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.old.test_h5t.TestCompound)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/h5py/h5py/.tox/py36-test-deps-pre/lib/python3.6/site-packages/h5py/tests/old/test_h5t.py", line 61, in test_out_of_order_offsets
    self.assertEqual(tid.dtype, expected_dtype)
AssertionError: dtype[13 chars]1','f3','f2'], 'formats':['<f4','<f8','<i4'], [30 chars]:20}) != dtype[13 chars]1','f2','f3'], 'formats':['<f4','<i4','<f8'], [30 chars]:20})
======================================================================
FAIL: test_out_of_order_offsets (h5py.tests.hl.test_datatype.TestOffsets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/h5py/h5py/.tox/py36-test-deps-pre/lib/python3.6/site-packages/h5py/tests/hl/test_datatype.py", line 198, in test_out_of_order_offsets
    self.assertArrayEqual(fd['data'], data)
  File "/home/travis/build/h5py/h5py/.tox/py36-test-deps-pre/lib/python3.6/site-packages/h5py/tests/common.py", line 124, in assertArrayEqual
    "Dtype mismatch (%s vs %s)%s" % (dset.dtype, arr.dtype, message)
AssertionError: False is not true : Dtype mismatch ({'names':['f1','f3','f2'], 'formats':['<f4','<f8','<i4'], 'offsets':[0,8,16], 'itemsize':20} vs {'names':['f1','f2','f3'], 'formats':['<f4','<i4','<f8'], 'offsets':[0,16,8], 'itemsize':20})
----------------------------------------------------------------------
```

Only one failure on 3.6 but it looks scary..

**Comment by aragilar** [comment]
Breaking because of numpy 1.14 change: https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst#multiple-field-indexingassignment-of-structured-arrays. My other recent PRs also fail because of this. Merging this and https://github.com/h5py/h5py/pull/954 should mean any failures are real. I'll try to produce a patch which works around/fixes the numpy changes.

**Comment by aragilar** [comment]
https://github.com/numpy/numpy/pull/6053 is the breaking change.

**Comment by aragilar** [comment]
Closing this, replaced by #970.

**Pull request closed without merging**
