### PR TITLE
FIX: Don't reorder compound types, breaks on numpy 1.14 

### PR DESCRIPTION
**Pull request by aragilar**
This removes the reordering of compound dtypes when written or read, needed on order for h5py to work on numpy 1.14 and later.

This includes #962, so that all the tests will pass on Travis. Appveyor may fail due to #954.

### CODE REVIEW

**Comment by tacaswell** [comment]
Do we need to document this as an API change?

**Comment by aragilar** [comment]
It should be strongly highlighted part of a release announcement (where we should recommend people upgrade to numpy 1.14 if they're using compound types). It's definitely an API change (the main breaking part will be when writing out out-of-order compound types), but it's fairly minimal in terms of actual breakage (reading should be unaffected, and in-order compound types are completely unaffected).

**Comment by tacaswell** [comment]
power-cycled to re-run CI.

Given the amount of other stuff this is broken we should probably merge this and cut a release ASAP.

Do we want to call the next release 2.7.2 or 2.8.0?

**Comment by aragilar** [comment]
Unless we only cherry-pick only the needed changes, calling a 2.8 release makes more sense.

@tacaswell Have you seen https://bors.tech/, I came across it recently, it allows retrying of tests and tests the merge, not just what's in the PR (rather than open/closing to retry, and having to rebase to check that the tests actually pass). It may be worth setting up after the 2.8 release.

**Comment by tacaswell** [comment]
Bumping to 2.8 does make some sense as it is easier to say (if numpy > =1.14 then h5py >=2.8) than on a micro.

**Comment by tacaswell** [comment]
Used the github web interface to fix the confilct.  Not _super_ happy about having master merged into the feature branch, but :man_shrugging: .

Will merge once this passes.

**Pull request merged**
