### PR TITLE
Update to last master

### PR DESCRIPTION
**Pull request by brunomartin**

### CODE REVIEW

**Comment by aragilar** [comment]
@brunomartin Did you mean to open this?

**Comment by brunomartin** [comment]
@aragilar, I may have done a bad request. I wanted to update my repo master to the last one, thank you for great work by the way.

The reason of my repos is to add capacity to flush/refresh group for root attributes in swmr mode.

Is that the right to operate ?

Thank you

**Comment by brunomartin** [comment]
By the way, I don’t mean to update the h5py master branch !

**Comment by brunomartin** [comment]
I closed this, sorry for the inconvenience.

**Pull request closed without merging**
