### PR TITLE
readme: replace google group with the HDF forum

### PR DESCRIPTION
**Pull request by FFY00**
The Google group is locked and the discussions have moved to the HDF
forum.

https://groups.google.com/g/h5py/c/9Eoz3vqlPZs

Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Comment by tacaswell** [comment]
Thanks @FFY00 !  The tests are failing because you need to add your self to the contributors file, see guidance at https://dev.azure.com/h5pyappveyor/h5py/_build/results?buildId=1112&view=logs&j=c4851542-858c-5aa0-9714-b02cde6c1394&t=230ae624-38df-5377-5338-7a322a9283fe&l=424

**Review by tacaswell — APPROVED** [review]
modulo getting CI to pass.

**Comment by takluyver** [comment]
It looks like it's now complaining that your Gmail address isn't in `.authors.yml`. I can only guess it's getting that from your Github profile. Sorry about this - I'm continually a bit baffled by the authors check. :confused:

**Comment by FFY00** [comment]
Uh, it seems that Github changed the email configurations and nuked the public email config as that is now configured in the profile page. I had not noticed this and updated the email shown in my profile to the one that should be there anyway, the one I specified in the authors file. Would it be possible to manually re-trigger the CI?

**Comment by takluyver** [comment]
Closing & reopening the PR should do it. :crossed_fingers:

**Comment by takluyver** [comment]
Nope, it still seems to find the gmail address. :confused: I'll try to look into re-ver and figure out what it's doing.

**Comment by takluyver** [comment]
OK, I've figured it out. It is getting emails from the commit log, but the commit that gets tested is a merge commit generated on Github (as if the PR was merged with master). That commit used your gmail address, even after you changed the publicly visible address on your profile. Perhaps it's the primary address on your account?

Anyway, that should mean that if I merge the PR, the real merge commit will be associated with me, and it should be happy... :crossed_fingers:

**Comment by takluyver** [comment]
Yup, it worked. Thanks for the PR :smile:

**Comment by takluyver** [comment]
I made an issue on rever for an option to avoid this problem: https://github.com/regro/rever/issues/250

**Pull request merged**
