### PR TITLE
Add `ndim` to Dataset

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/h5py/h5py/issues/638

Requires https://github.com/h5py/h5py/pull/656
Requires https://github.com/h5py/h5py/pull/653

Simply finds the length of shape.

### CODE REVIEW

**Comment by jakirkham** [comment]
I think can and maybe should be cached, but I am not sure how that is being done currently. So, could use a few pointers.

**Comment by jakirkham** [comment]
Added some method of caching. There is probably a better one.

**Comment by jakirkham** [comment]
Could use some pointers on how to test this.

**Comment by andreabedini** [comment]
isn't this the same as [Dataset.rank](https://github.com/jakirkham/h5py/blob/add_ndim/h5py/h5d.pyx#L140)?

**Comment by jakirkham** [comment]
Really? I don't seem to be able to use `rank` on `Dataset`s. It looks like this commit is really old and I am on `2.5.0` so I am not sure why this is.

In any event, the point of the addition of `ndim` here is to be more duck type friendly with regards to `numpy.ndarray`s. There is no `rank` for them and `ndim` is heavily used.

**Comment by andrewcollette** [comment]
@jakirkham, it looks like you have accidentally added .ndim to the low-level DatasetID in h5d.pyx.  I think the class you are looking for is in h5py/_hl; you could do something like the following:

```
@property
def ndim(self):
    return self.id.rank
```

**Comment by jakirkham** [comment]
Thanks for the pointer, @andrewcollette. I have done exactly that and tried to add some tests. They seem ok, but I would like to see the tests pass. Let me know if you would have them changed and/or moved somewhere else.

**Comment by jakirkham** [comment]
Alright, looks like the tests are passing. Ready for more feedback, if needed.

**Comment by jakirkham** [comment]
Had added some tests for `Dataset.shape`, but have broken them out in this PR ( https://github.com/h5py/h5py/pull/653 ) for separate consumption.

**Comment by jakirkham** [comment]
`pylint` was giving me some grief as it was rules in `pylintrc` so I had to pin the version to something more reasonable.

**Comment by jakirkham** [comment]
How does this look so far?

**Comment by andrewcollette** [comment]
Looks good... thanks.

**Comment by jakirkham** [comment]
Think I forgot a `with_phil` decorator. At least, I think it is needed here. So, I put it in this PR ( https://github.com/h5py/h5py/pull/660 ).

**Pull request merged**
